### ISSUE TITLE
Clear Commands Effect

### ISSUE THREAD

**Issue by laigelplayz** [MihaiChirculete/WorldGuard#176]
**Describe the bug**
Clears my Potion Effects

1. When i travel through regions it will clear all my effects that is from commands but if i use bottles it didnt
2. I can't open my KitPvP gamemode until its fixed Kitpvp is the main gamemode of my Server:(
3. Only clears Commands effect like /effect
4. Doesn't clears Bottle effects

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ItsMax123** [comment]
Same thing happens to me... Why was this issue closed without an answer given?

**Comment by awgybop1** [comment]
He closed the issue himself, don't know why.
We're working on a new update to save effects given by the plugin and take only those away when you leave the region.
This is very annoying to do because:
1.) We have to account for the effects the player already had.
2.) What to do if the player has for ex. Speed 2 and the region gives them Speed 1.
3.) Saving not only the effect, but also its time left without changing what they had originally.
4.) Managing this within a database so that it saves over restarts.
5.) Doing this without messing up or allowing exploits to be found for infinite effects.
6.) All the unforeseen bugs that come with this system.

The update WILL happen, we're just still developing a system to get this done - as well as create an API for the plugin, fix pre-existing bugs, etc.
There are only 3 people actively working on WorldGuard right now, and we're all very caught up in life and can't work on the plugin as much as we could before.

**Comment by ItsMax123** [comment]
ok
also btw I think most people who are getting this bug are getting because of PiggyCustomEnchants
at least that what the problem is for me
Also last thing I know you are all very busy but do you know why the default mc pearl cooldown gets removed when someone is in a worldguard area?

**Comment by suerion** [comment]
with #185 it should already fixed,

PiggyCustomEnchants should not deleted anymore

**Comment by ItsMax123** [comment]
Oh ok thanks a lot! This commit isn't pushed to poggit right? cuz I have the lastest poggit version.

**Comment by suerion** [comment]
we know about it, we will look on our new update

**Comment by awgybop1** [comment]
@ItsMax123 Poggit builds are only pushed when the plugin is 100% tested by us for all features to be working as expected.
This means that the updates come very slowly as we only submit the plugin when we've fixed everything people have reported that seriously affects the gameplay and/or stability of their servers.

**Comment by suerion** [comment]
should fixed with #194
